# Generated by Django 5.2.5 on 2025-09-01 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200)),
                ('permit_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(editable=False)),
                ('renewed', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_yearly', models.BooleanField(default=False)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_daily', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(choices=[('saloon', 'Saloon Car'), ('van', 'Van'), ('bus_lorry', 'Bus / Small Lorry'), ('truck_tanker', 'Truck / Tanker')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_custom', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='revenue.area')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_place', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.PositiveIntegerField()),
                ('time_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('plate_number', models.CharField(max_length=40)),
                ('vehicle_type', models.CharField(max_length=40)),
                ('town_name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.parkingsection')),
            ],
        ),
    ]
