# Generated by Django 5.2.5 on 2025-09-01 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revenue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.permittype'),
        ),
        migrations.AddField(
            model_name='area',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='revenue.town'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.vehicle'),
        ),
    ]
